{
    'name': 'THT CINEMA API',
    'description': 'THT CINEAM API  20211107',
    'category': '',
    'sequence': 120,
    'version': '1.1',
    'author': 'Tien, Hieu',
    'depends': ['website', 'tht_cinema', 'portal', 'website_blog'],
    'data': [
        'views/blog_post.xml',
        # 'views/assets.xml',
        # 'views/website_templates.xml',
        # 'views/muave.xml',
        # 'views/phim_lichchieu_all.xml',
        # 'views/datve.xml',
        # 'data/menu.xml',
        # 'views/momo_dbv.xml',
        # 'views/cash_dbv.xml',
        # 'views/momo.xml',
        # 'views/user_dbv.xml',
        # 'views/soatve.xml',
        # 'views/soatve_result.xml',
        # 'views/user_momo_error.xml',
        # 'views/website_menu.xml',
        # 'views/portal_dbv.xml',

        # 'views/dangchieu.xml',
        # 'views/lichchieu.xml',
        # 'views/sapchieu.xml',

        # 'views/customize_modal.xml',
        # 'views/image_content.xml',
        # 'views/image_library.xml',
        # 'views/snippets_options.xml',
        # 'views/snippets.xml',
        # 'views/options.xml',
    ],
    'demo': [
        # 'demo/home.xml',
        # 'demo/blocks.xml',
    ],
    'images': [
        # 'static/description/Clean_description.jpg',
        # 'static/description/clean_screenshot.jpg',
    ],
    
}
